#ifndef PRIMITIVETYPES_H
#define PRIMITIVETYPES_H

namespace Gapi
{
	typedef enum PrimitiveTypes
	{
		EPT_POINTLIST = 0xFE12,
		EPT_LINELIST = 0xFDBE,
		EPT_LINESTRIP = 0x6B83,
		EPT_TRIANGLELIST = 0x7DD0,
		EPT_TRIANGLESTRIP = 0x9FAE
	} PRIMITIVETYPES;
}

#endif // PRIMITIVETYPES_H