#ifndef VERTEXELEMENTTYPES_H
#define VERTEXELEMENTTYPES_H

namespace Gapi
{
	typedef enum VertexElementTypes
	{
		EVET_POSITION = 0x0605,
		EVET_COLOR = 0x3407,
		EVET_TEXCOORD = 0x309F,
		EVET_NORMAL = 0x8CB7,
		EVET_TANGENT = 0x549F,
		EVET_BITANGENT = 0x5018
	} VERTEXELEMENTTYPES;
}

#endif // VERTEXELEMENTTYPES_H